"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['MyIds.py']
DATA_FILES = ['image_1.png', 'entry_1.png', 'entry_2.png', 'entry_3.png', 'entry_4.png', 'button_1.png', 'button_2.png', 'button_3.png', 'button_4.png']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
